services:
  pdf_server:
    build: .
    container_name: pdf_server
    ports:
      - "8000:8000"
    volumes:
      #change this to the directory that must run on the server
      - "D:/lectures(anul 4)/Programarea in retea/Laboratory 1 -HTTP Server/contents : /app/contents"
    command: ["python", "server.py", "contents"]
